version: '2'

services:
    jaeger-collector:
      image: registry.cn-hangzhou.aliyuncs.com/jaegertracing/jaeger-collector:0.0.3
      environment:
        - SPAN_STORAGE_TYPE=aliyun-log
      command: ["/go/bin/collector-linux", "--aliyun-log.project=${PROJECT}", "--aliyun-log.endpoint=${ENDPOINT}", "--aliyun-log.access-key-id=${ACCESS_KEY_ID}", "--aliyun-log.access-key-secret=${ACCESS_KEY_SECRET}", "--aliyun-log.span-logstore=${SPAN_LOGSTORE}"]
      ports:
        - "14269"
        - "14268:14268"
        - "14267"
        - "9411:9411"
      restart: on-failure

    jaeger-query:
      image: registry.cn-hangzhou.aliyuncs.com/jaegertracing/jaeger-query:0.0.3
      environment:
        - SPAN_STORAGE_TYPE=aliyun-log
      command: ["/go/bin/query-linux", "--query.static-files=/go/jaeger-ui/", "--aliyun-log.project=${PROJECT}", "--aliyun-log.endpoint=${ENDPOINT}", "--aliyun-log.access-key-id=${ACCESS_KEY_ID}", "--aliyun-log.access-key-secret=${ACCESS_KEY_SECRET}", "--aliyun-log.span-logstore=${SPAN_LOGSTORE}"]
      ports:
        - "16686:16686"
        - "16687"
      restart: on-failure

    jaeger-agent:
      image: jaegertracing/jaeger-agent
      command: ["--collector.host-port=jaeger-collector:14267"]
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
      restart: on-failure
      depends_on:
        - jaeger-collector



